version: '3.8'
services:
  webapi:
    image: webapi3:latest
    container_name: webapi
    restart: always
    ports:
      - "80:5000"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=SensorDataDb;Username=postgres;Password=LvBFYtn9UJh!
