version: '3.8'
services:
  webapi:
    image: webapi5:latest
    container_name: webapi
    restart: always
    ports:
      - "80:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=SensorDataDb;Username=postgres;Password=LvBFYtn9UJh!
